### ISSUE TITLE
Error with android-media-picker

### ISSUE THREAD

**Issue by ghost** [Turtlebody/android-media-picker#2]
I cloned this project and add in android studio.
 But the output was:
Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/

How can i solve this.

**Comment by nirajprakash** [comment]
I will look into it. Will inform you once updated.

**Comment by Marcosmaliki** [comment]
just replace 'compile' in app > gradle with 'implementation'

**Comment by wangsun6** [comment]
follow @Marcosmaliki suggestion and make sure to use latest version Android Studio
