### ISSUE TITLE
Media picker issues

### ISSUE THREAD

**Issue by Marcosmaliki** [Turtlebody/android-media-picker#3]
I have a problem with a superclass used in the library. Check my log 

Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:     class com.greentoad.turtlebody.mediapicker.MediaPicker.MediaPickerImpl, unresolved supertypes: org.jetbrains.anko.AnkoLogger     class com.greentoad.turtlebody.mediapicker.MediaPicker.PickerFragment, unresolved supertypes: org.jetbrains.anko.AnkoLogger   > Task :app:buildInfoGeneratorDebug |  
-- | --

**Comment by Marcosmaliki** [comment]
I found a solution, a dependency is missing:
    //anko
    implementation "org.jetbrains.anko:anko-commons:$ANKO_VERSION"
I added it to my gradle and everything is working perfectly. Thanks for the library

**Comment by wangsun6** [comment]
yup as @Marcosmaliki  said u can add missing dependency "implementation "org.jetbrains.anko:anko:Version" to remove the error.

in next version we will remove this dependent dependency.
