### ISSUE TITLE
Return raw data from Intent 

### ISSUE THREAD

**Issue by Marcosmaliki** [Turtlebody/android-media-picker#5]
Is it possible to get data: Intent array too?
I can't get the file from the provided Uri. I want the file to upload to the server

**Comment by wangsun6** [comment]
we have tested this uri in many libraries and it works file. tested in firebase, glide etc
you will not get file from this uri since this document file.

getting document file:
'
var a = DocumentFile.fromSingleUri(this,uri)
'
