### ISSUE TITLE
comman list for images & video 

### ISSUE THREAD

**Issue by mansiJspaceo** [Turtlebody/android-media-picker#9]
how can we get all list of images & video in same .user can   select both  images & video

**Comment by wangsun6** [comment]
Our UI is designed in such a way that only single type will be shown at a particular time. So there is no way you can list both images and videos at same ui.
But at your end(your app) you can do some tricks to get list of both selected images and videos.

Whenever you select images or videos, you get the file uri in return. so give the user option to select images or videos but whenever you get selected uri add it in single arrayList. and final list will contain both images and videos uri's.
